// export { default as SocialProof } from './SocialProof'
export { default as HeroSlice } from './HeroSlice'
export { default as FeatureSlice } from './FeatureSlice'
export { default as NavbarSlice } from './NavbarSlice'
export { default as CallToAction } from './CallToAction'
export { default as FaqSlice } from './FaqSlice'
export { default as SimpleFooter } from './SimpleFooter'
export { default as FormSlice } from './FormSlice'